<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\Route;

/*
 * DDE-Mart — API reference generator (original command).
 * Regenerates docs/api-v1.md from the registered v1 route table so the
 * mobile teams always see an accurate method/path/auth matrix. Usage notes
 * (auth flows, envelopes) are hand-written in the header below.
 */
class GenerateApiDocs extends Command
{
    protected $signature = 'ddemart:api-docs';

    protected $description = 'Regenerate docs/api-v1.md from the v1 route table';

    public function handle(): int
    {
        $rows = [];

        foreach (Route::getRoutes() as $route) {
            $uri = $route->uri();

            if (! str_starts_with($uri, 'api/v1')) {
                continue;
            }

            $methods = implode('|', array_diff($route->methods(), ['HEAD']));
            $middleware = implode(',', array_filter($route->gatherMiddleware(), fn ($m) => in_array($m, [
                'auth:sanctum', 'abilities:customer', 'abilities:driver', 'ability:vendor,owner', 'abilities:provider', 'throttle:api-auth',
            ], true)));

            $rows[] = [$methods, '/'.$uri, $middleware, $route->getActionMethod()];
        }

        usort($rows, fn ($a, $b) => [$a[1], $a[0]] <=> [$b[1], $b[0]]);

        $groups = [
            'Customer auth' => fn ($u) => str_starts_with($u, '/api/v1/auth'),
            'Workforce auth' => fn ($u) => str_starts_with($u, '/api/v1/work/auth'),
            'Public catalog & content' => fn ($u) => (bool) preg_match('#^/api/v1/(sections|categories|products|stores|banners|ads|settings|onboarding|languages|pages|notifications)#', $u),
            'Customer account & commerce' => fn ($u) => (bool) preg_match('#^/api/v1/(me|cart|coupons|checkout|orders|wallet|favorites)#', $u),
            'Customer bookings & life' => fn ($u) => (bool) preg_match('#^/api/v1/(parcel|rental|rides|services|service-|dinein|gifts|gift-|reviews|complaints|sos|push-tokens|chat|uploads)#', $u),
            'Driver app' => fn ($u) => str_starts_with($u, '/api/v1/driver'),
            'Vendor app' => fn ($u) => str_starts_with($u, '/api/v1/vendor'),
            'Provider app' => fn ($u) => str_starts_with($u, '/api/v1/provider'),
        ];

        $md = <<<'MD'
            # DDE-Mart API v1 — reference

            > Regenerated by `php artisan ddemart:api-docs`. Do not edit the tables by hand.

            Base URL: `https://<host>/api/v1` · JSON only (`Accept: application/json`).

            ## Auth

            - **Customers:** `POST /auth/register` (name+phone, optional password) or `POST /auth/login`
              (phone+password), or OTP (`/auth/otp/request` → `/auth/otp/verify`). Responses carry
              `data.token` — send as `Authorization: Bearer <token>`. Ability: `customer`.
            - **Workforce (driver/vendor/owner/provider):** OTP only — `POST /work/auth/otp/request`
              `{phone, role}` then `/work/auth/otp/verify` `{phone, role, code}`. In non-production the
              request response includes `data.debug_code`. Token ability equals the role; vendor and
              owner share the `vendor`/`owner` surfaces (either ability suffices).
            - **Guests:** catalog/content feeds are public; everything else 401s without a token.

            ## Conventions

            - Lists: `{"data": [...], "meta": {"current_page", "last_page", "total"}}`, `?per_page=` (max 50).
            - Errors: `{"message": "..."}` with 401 (guest), 403 (wrong audience), 404 (foreign record),
              422 (validation / illegal transition / unconfigured gateway).
            - Push: apps register FCM tokens at `<role>/push-tokens` and subscribe to their topic
              (`vendors` / `providers` / `drivers`) for new-order/booking/job broadcasts.
            - Wallet top-up: `POST <role-or-customer>/wallet/topup` → `redirect_url`; the callback URL
              verifies with the gateway, then credits once (idempotent on the gateway reference).

            MD;

        $used = [];

        foreach ($groups as $title => $match) {
            $md .= "\n## {$title}\n\n| Method | Path | Auth | Handler |\n|---|---|---|---|\n";

            foreach ($rows as $i => $row) {
                if (isset($used[$i]) || ! $match($row[1])) {
                    continue;
                }

                $used[$i] = true;
                $md .= sprintf("| %s | `%s` | %s | %s |\n", $row[0], $row[1], $row[2] === '' ? 'public' : '`'.$row[2].'`', $row[3]);
            }
        }

        $rest = array_filter(array_keys($rows), fn ($i) => ! isset($used[$i]));

        if ($rest !== []) {
            $md .= "\n## Other\n\n| Method | Path | Auth | Handler |\n|---|---|---|---|\n";

            foreach ($rest as $i) {
                $row = $rows[$i];
                $md .= sprintf("| %s | `%s` | %s | %s |\n", $row[0], $row[1], $row[2] === '' ? 'public' : '`'.$row[2].'`', $row[3]);
            }
        }

        $path = base_path('docs/api-v1.md');
        file_put_contents($path, $md);
        $this->info('Wrote docs/api-v1.md ('.count($rows).' routes).');

        return self::SUCCESS;
    }
}
